module.exports = {
  "Engineering Physics": {
    topicDesc: "Complete academic mapping of JNTUK Engineering Physics R23 curriculum. From quantum tunneling to advanced semiconductor transport.",
    units: [
      {
        id: "unit-2",
        title: "Wave Particle Duality & Schrödinger Mechanics",
        subtitle: "Unit II: Quantum Mechanics & Free Electron Theory",
        weightage: "~15-20 Marks",
        desc: "Dual nature of matter, Heisenberg uncertainty, Schrödinger wave equations, and 1D potential wells.",
        introTitle: "Introduction to Quantum States",
        introBody: "Classical mechanics fails at the atomic scale. Quantum mechanics introduces wave-particle duality, where matter exhibits both particle-like and wave-like behavior, governed by probability amplitudes.",
        coreHighlight: "The Core Crux of R23: The entire unit revolves around the exact boundary state derivations for the 1D infinite potential well and the implications of the Heisenberg Uncertainty Principle.",
        concept1: { title: "Matter Waves", detail: "de Broglie proposed that moving particles have an associated wavelength λ = h/p." },
        concept2: { title: "Uncertainty", detail: "Heisenberg formulated that position and momentum cannot be simultaneously measured with arbitrary precision: Δx · Δp ≥ h/4π." },
        formula1: { title: "de Broglie Wavelength", eq: "λ = h / √(2mE)" },
        formula2: { title: "Particle in 1D Box", eq: "E_n = n²h² / (8mL²)" },
        pyq1: { title: "Schrödinger Time-Independent Eq", marks: "10 Marks", body: "Derive the time independent Schrödinger wave equation." },
        pyq2: { title: "Fermi Dirac Distribution", marks: "5 Marks", body: "Explain the effect of temperature on Fermi-Dirac distribution function." },
      },
      {
        id: "unit-3",
        title: "Intrinsic & Extrinsic Carrier Transport",
        subtitle: "Unit III: Semiconductors",
        weightage: "~15-20 Marks",
        desc: "Intrinsic/extrinsic transport, drift/diffusion, Fermi levels, and the Hall Effect.",
        introTitle: "Semiconductor Band Theory",
        introBody: "Materials are classified by energy band gaps. Semiconductors have a small band gap (~1 eV) allowing thermal excitation.",
        coreHighlight: "The Core Crux of R23: Hall effect derivation, Einstein relation, and intrinsic carrier concentration derivations dominate the board exams.",
        concept1: { title: "Charge Carriers", detail: "Electrons in conduction band and holes in valence band contribute to current." },
        concept2: { title: "Hall Effect", detail: "A transverse voltage is produced when a magnetic field is applied perpendicular to current flow." },
        formula1: { title: "Intrinsic Density", eq: "n_i² = N_c N_v exp(-E_g/kT)" },
        formula2: { title: "Hall Coefficient", eq: "R_H = 1 / (n·e)" },
        pyq1: { title: "Hall Effect Derivation", marks: "10 Marks", body: "Explain Hall Effect. Derive the expression for Hall coefficient." },
        pyq2: { title: "Einstein Relation", marks: "5 Marks", body: "Deduce the Einstein’s relation between diffusion coefficient and mobility." },
      },
      {
        id: "unit-4",
        title: "Einstein Coefficients & Fiber Optics",
        subtitle: "Unit IV: Lasers & Fiber Optics",
        weightage: "~10-15 Marks",
        desc: "Laser Characteristics, He-Ne laser, Nd:YAG. Numerical Aperture, Acceptance Angle derivations.",
        introTitle: "Principles of Light Emission",
        introBody: "Lasers operate on stimulated emission. Fiber optics rely on total internal reflection for guided light transmission.",
        coreHighlight: "The Core Crux of R23: He-Ne laser working mechanism and Numerical Aperture derivations are repeated every year.",
        concept1: { title: "Stimulated Emission", detail: "An incoming photon stimulates an excited atom to emit a coherent photon." },
        concept2: { title: "Total Internal Reflection", detail: "Light traveling from denser to rarer medium reflects completely if angle > critical angle." },
        formula1: { title: "Numerical Aperture", eq: "NA = √(n₁² - n₂²)" },
        formula2: { title: "Acceptance Angle", eq: "θ_a = arcsin(NA)" },
        pyq1: { title: "He-Ne Laser", marks: "10 Marks", body: "With a neat energy level diagram describe the working of He-Ne laser." },
        pyq2: { title: "Numerical Aperture", marks: "5 Marks", body: "Derive an expression for acceptance angle and numerical aperture." },
      },
      {
        id: "unit-5",
        title: "Polarization & Superconductors",
        subtitle: "Unit V: Dielectric & Magnetic Materials",
        weightage: "~10-15 Marks",
        desc: "Dielectrics polarizations; internal fields. Origin of magnetic moment, ferromagnetism, Superconducting transition.",
        introTitle: "Material Responses to Fields",
        introBody: "Dielectrics polarize in electric fields. Magnetic materials align dipoles in magnetic fields. Superconductors expel magnetic fields perfectly.",
        coreHighlight: "The Core Crux of R23: Clausius-Mossotti relation, B-H curve, and Meissner effect are the guaranteed questions.",
        concept1: { title: "Polarization", detail: "Electronic, ionic, and orientational displacement of charges." },
        concept2: { title: "Meissner Effect", detail: "Expulsion of magnetic field lines from a superconductor below critical temperature (perfect diamagnetism)." },
        formula1: { title: "Clausius-Mossotti", eq: "(ε_r - 1)/(ε_r + 2) = (N_α)/(3ε_o)" },
        formula2: { title: "Critical Field", eq: "H_c(T) = H_c(0)[1 - (T/T_c)²]" },
        pyq1: { title: "Clausius-Mossotti Relation", marks: "10 Marks", body: "Derive Clausius-Mossotti relation for solid dielectrics." },
        pyq2: { title: "Meissner Effect", marks: "5 Marks", body: "Write a short note on Meissner effect and Type I & II superconductors." },
      }
    ]
  },
  "Engineering Mathematics": {
    topicDesc: "Complete mapping of JNTUK Engineering Mathematics M1 & M2. From Matrix Eigenvalues to Multivariable Calculus.",
    units: [
      {
        id: "unit-1",
        title: "Matrix Operations & Linear Systems",
        subtitle: "Unit I: Matrices",
        weightage: "~15-20 Marks",
        desc: "Rank of matrix, Echelon form, Normal form. Solution of linear systems. Gauss elimination.",
        introTitle: "Linear Algebra Fundamentals",
        introBody: "Matrices provide a compact way to represent and solve systems of linear equations.",
        coreHighlight: "The Core Crux of R23: Finding the Rank using Echelon form and testing consistency of linear equations.",
        concept1: { title: "Rank of a Matrix", detail: "Number of non-zero rows in its row echelon form." },
        concept2: { title: "Gauss Elimination", detail: "Reducing a system to upper triangular form to solve via back substitution." },
        formula1: { title: "Consistency", eq: "Rank(A) = Rank(A|B) ≤ n" },
        formula2: { title: "Infinite Solutions", eq: "Rank(A) = Rank(A|B) < n" },
        pyq1: { title: "Rank by Normal Form", marks: "10 Marks", body: "Reduce the matrix to Normal form and find its rank." },
        pyq2: { title: "System Consistency", marks: "10 Marks", body: "Test for consistency and solve: 2x - y + 3z = 8, -x + 2y + z = 4, 3x + y - 4z = 0." },
      },
      {
        id: "unit-2",
        title: "Eigenvalues, Eigenvectors & Orthogonal Transformation",
        subtitle: "Unit II: Eigen-Systems",
        weightage: "~15-20 Marks",
        desc: "Eigenvalues, Eigenvectors, Cayley-Hamilton Theorem, Diagonalization, Quadratic forms to canonical forms.",
        introTitle: "Eigen-Systems & Transformations",
        introBody: "Eigenvalues provide characteristic scale factors for matrix transformations. Cayley-Hamilton connects a matrix to its characteristic polynomial.",
        coreHighlight: "The Core Crux of R23: Finding Eigenvalues/vectors and reducing Quadratic form to Canonical form by Orthogonal Transformation.",
        concept1: { title: "Cayley-Hamilton Theorem", detail: "Every square matrix satisfies its own characteristic equation." },
        concept2: { title: "Quadratic Form", detail: "A homogenous polynomial of degree 2 in a number of variables." },
        formula1: { title: "Characteristic Eq", eq: "|A - λI| = 0" },
        formula2: { title: "Quadratic Form", eq: "Q = X^T A X" },
        pyq1: { title: "Cayley-Hamilton", marks: "10 Marks", body: "Verify Cayley-Hamilton theorem and find the inverse of A." },
        pyq2: { title: "Quadratic to Canonical", marks: "10 Marks", body: "Reduce the given quadratic form to canonical form by orthogonal reduction." }
      },
      {
        id: "unit-3",
        title: "Calculus & Mean Value Theorems",
        subtitle: "Unit III: Differential Calculus",
        weightage: "~15 Marks",
        desc: "Mean Value Theorems: Rolle's, Lagrange's, Cauchy's. Taylor's and Maclaurin's series.",
        introTitle: "Differential Calculus & Series",
        introBody: "Mean value theorems connect the local derivative of a function to its global change. Series expansions approximate complex functions with polynomials.",
        coreHighlight: "The Core Crux of R23: Verifying Rolle's/Lagrange's theorems and expanding functions using Maclaurin's series.",
        concept1: { title: "Rolle's Theorem", detail: "If f(a)=f(b) and continuous, there exists c where f'(c)=0." },
        concept2: { title: "Maclaurin Series", detail: "Expansion of a function about x=0." },
        formula1: { title: "Lagrange's MVT", eq: "f'(c) = (f(b) - f(a)) / (b - a)" },
        formula2: { title: "Cauchy's MVT", eq: "f'(c)/g'(c) = (f(b)-f(a))/(g(b)-g(a))" },
        pyq1: { title: "Verify Lagrange's MVT", marks: "5 Marks", body: "Verify Lagrange's mean value theorem for f(x) = log(x) on [1, e]." },
        pyq2: { title: "Maclaurin Expansion", marks: "10 Marks", body: "Expand tan(x) up to the term containing x^5 using Maclaurin's series." }
      },
      {
        id: "unit-4",
        title: "Partial Differentiation & Applications",
        subtitle: "Unit IV: Multivariable Calculus",
        weightage: "~15-20 Marks",
        desc: "Partial derivatives, Jacobians, Maxima and minima of functions of two variables, Lagrange multipliers.",
        introTitle: "Multivariable Calculus",
        introBody: "Extending calculus to functions of multiple variables. Critical for optimizing systems with multiple inputs.",
        coreHighlight: "The Core Crux of R23: Finding Maxima/Minima of two variables and applying Lagrange's method of undetermined multipliers.",
        concept1: { title: "Jacobian", detail: "Determinant of the Jacobian matrix, used in change of variables." },
        concept2: { title: "Lagrange Multipliers", detail: "Optimizing a function subject to equality constraints." },
        formula1: { title: "Total Derivative", eq: "dz = (∂z/∂x)dx + (∂z/∂y)dy" },
        formula2: { title: "Lagrange Function", eq: "L = f(x,y) + λφ(x,y)" },
        pyq1: { title: "Maxima & Minima", marks: "10 Marks", body: "Find the maximum and minimum values of x^3 + 3xy^2 - 15x^2 - 15y^2 + 72x." },
        pyq2: { title: "Jacobians", marks: "5 Marks", body: "If u = x+y, v = xy, find the Jacobian ∂(u,v)/∂(x,y)." }
      },
      {
        id: "unit-5",
        title: "Multiple Integrals",
        subtitle: "Unit V: Multiple Integration",
        weightage: "~15 Marks",
        desc: "Double and triple integrals, change of order of integration, change of variables, finding areas and volumes.",
        introTitle: "Multiple Integration",
        introBody: "Extending definite integrals to two and three dimensions for calculating areas, volumes, and center of mass.",
        coreHighlight: "The Core Crux of R23: Change of order of integration and evaluating double integrals over specific regions.",
        concept1: { title: "Change of Order", detail: "Swapping the limits of integration to simplify evaluation." },
        concept2: { title: "Polar Coordinates", detail: "Transforming Cartesian (x,y) to Polar (r,θ) where dx dy = r dr dθ." },
        formula1: { title: "Area via Double Integral", eq: "A = ∬ dx dy" },
        formula2: { title: "Volume via Triple Integral", eq: "V = ∭ dx dy dz" },
        pyq1: { title: "Change of Order", marks: "10 Marks", body: "Change the order of integration and evaluate ∬ xy dx dy." },
        pyq2: { title: "Area Calculation", marks: "5 Marks", body: "Find the area enclosed by the curves y = x^2 and y = x." }
      }
    ]
  },
  "Data Structures": {
    topicDesc: "Complete mapping of JNTUK Data Structures R23. From basic Arrays to advanced Graph traversal topologies.",
    units: [
      {
        id: "unit-1",
        title: "Arrays, Searching & Sorting",
        subtitle: "Unit I: Fundamentals",
        weightage: "~15 Marks",
        desc: "Array operations, Linear/Binary search. Selection, Bubble, Insertion, Quick, Merge sort.",
        introTitle: "Data Organization",
        introBody: "Organizing data efficiently is the foundation of computer science. Searching and sorting are the baseline mechanics.",
        coreHighlight: "The Core Crux of R23: Time complexity derivations for Merge Sort and Quick Sort.",
        concept1: { title: "Binary Search", detail: "O(log n) search on a sorted array by repeated halving." },
        concept2: { title: "Merge Sort", detail: "Divide and conquer recursive algorithm. Guaranteed O(n log n) time." },
        formula1: { title: "Binary Search Time", eq: "T(n) = T(n/2) + O(1)" },
        formula2: { title: "Merge Sort Time", eq: "T(n) = 2T(n/2) + O(n)" },
        pyq1: { title: "Quick Sort", marks: "10 Marks", body: "Trace Quick Sort on the array: [40, 20, 10, 80, 60, 50, 7, 30, 100]." },
        pyq2: { title: "Binary Search", marks: "5 Marks", body: "Write a C function for iterative Binary Search and state its complexity." },
      },
      {
        id: "unit-2",
        title: "Linked Lists (SLL, DLL, CLL)",
        subtitle: "Unit II: Dynamic Structures",
        weightage: "~15-20 Marks",
        desc: "Singly linked lists, doubly linked lists, circular linked lists, representation and operations.",
        introTitle: "Dynamic Data Structures",
        introBody: "Unlike arrays, linked lists allocate memory dynamically and do not require contiguous memory blocks.",
        coreHighlight: "The Core Crux of R23: Programmatic implementation of insertion and deletion in Singly and Doubly Linked Lists.",
        concept1: { title: "Singly Linked List", detail: "Each node contains data and a pointer to the next node." },
        concept2: { title: "Doubly Linked List", detail: "Each node contains pointers to both the previous and next nodes." },
        formula1: { title: "SLL Node Structure", eq: "struct Node { int data; struct Node* next; };" },
        formula2: { title: "DLL Node Structure", eq: "struct Node { int data; struct Node* prev, *next; };" },
        pyq1: { title: "SLL Operations", marks: "10 Marks", body: "Write a C program to insert a node at the beginning and end of a Singly Linked List." },
        pyq2: { title: "DLL Deletion", marks: "5 Marks", body: "Write an algorithm to delete a specific node from a Doubly Linked List." }
      },
      {
        id: "unit-3",
        title: "Stacks & Applications",
        subtitle: "Unit III: LIFO Operations",
        weightage: "~15 Marks",
        desc: "Stack properties, operations, array and linked list implementation, expression evaluation.",
        introTitle: "LIFO Operations",
        introBody: "Stacks follow the Last-In-First-Out (LIFO) principle. They are fundamental in recursion and parsing.",
        coreHighlight: "The Core Crux of R23: Conversion of infix to postfix expressions and evaluating postfix expressions.",
        concept1: { title: "Push & Pop", detail: "Push adds an element to the top; Pop removes the top element." },
        concept2: { title: "Expression Parsing", detail: "Using stacks to evaluate postfix expressions or check balanced parentheses." },
        formula1: { title: "Push Operation", eq: "stack[++top] = value;" },
        formula2: { title: "Pop Operation", eq: "value = stack[top--];" },
        pyq1: { title: "Infix to Postfix", marks: "10 Marks", body: "Convert the infix expression (A+B)*C-D/E into postfix notation using a stack." },
        pyq2: { title: "Stack via Linked List", marks: "10 Marks", body: "Implement Stack push and pop operations using Linked List." }
      },
      {
        id: "unit-4",
        title: "Queues & Deques",
        subtitle: "Unit IV: FIFO Operations",
        weightage: "~15 Marks",
        desc: "Queue properties, operations, circular queues, deques, implementation using arrays/linked lists.",
        introTitle: "FIFO Operations",
        introBody: "Queues operate strictly on First-In-First-Out (FIFO) logic, essential for scheduling and buffering.",
        coreHighlight: "The Core Crux of R23: Circular queue implementation and its advantage over simple queues.",
        concept1: { title: "Enqueue & Dequeue", detail: "Enqueue adds to the rear; Dequeue removes from the front." },
        concept2: { title: "Circular Queue", detail: "Connects the last position back to the first to utilize empty space efficiently." },
        formula1: { title: "CQ Enqueue", eq: "rear = (rear + 1) % MAX;" },
        formula2: { title: "CQ Dequeue", eq: "front = (front + 1) % MAX;" },
        pyq1: { title: "Circular Queue Operations", marks: "10 Marks", body: "Explain the implementation of Circular Queue with suitable C functions." },
        pyq2: { title: "Deque", marks: "5 Marks", body: "What is a Double Ended Queue (Deque)? Explain its input restricted variant." }
      },
      {
        id: "unit-5",
        title: "Trees, Hashing & Graphs",
        subtitle: "Unit V: Non-Linear Structures",
        weightage: "~20 Marks",
        desc: "Trees, Binary Search Tree (Insertion/Deletion/Traversal), Hashing collision techniques, Graph traversals.",
        introTitle: "Non-Linear Structures & Maps",
        introBody: "Hierarchical data is represented using Trees, while interconnected network systems use Graphs.",
        coreHighlight: "The Core Crux of R23: BST traversals (Inorder, Preorder, Postorder) and BFS/DFS graph traversals.",
        concept1: { title: "Binary Search Tree", detail: "Left child < Root < Right child, allowing efficient O(log n) searching." },
        concept2: { title: "Graph Traversal", detail: "BFS uses a Queue; DFS uses a Stack (or recursion)." },
        formula1: { title: "BST Property", eq: "Left_Val < Root_Val < Right_Val" },
        formula2: { title: "Hash Function", eq: "index = key % SIZE;" },
        pyq1: { title: "Tree Traversals", marks: "10 Marks", body: "Construct a BST for: 50, 30, 20, 40, 70, 60, 80. Write its Inorder, Preorder and Postorder." },
        pyq2: { title: "BFS and DFS", marks: "10 Marks", body: "Explain Breadth First Search (BFS) and Depth First Search (DFS) with an example." }
      }
    ]
  }
}
