module.exports = {
  "Engineering Physics": {
    topicDesc: "Complete academic mapping of JNTUK Engineering Physics R23 curriculum. From quantum tunneling to advanced semiconductor transport.",
    units: [
      {
        id: "unit-2",
        title: "Wave Particle Duality & Schrödinger Mechanics",
        subtitle: "Unit II: Quantum Mechanics & Free Electron Theory",
        weightage: "~15-20 Marks",
        desc: "Dual nature of matter, Heisenberg uncertainty, Schrödinger wave equations, and 1D potential wells.",
        introTitle: "Introduction to Quantum States",
        introBody: "Classical mechanics fails at the atomic scale. Quantum mechanics introduces wave-particle duality, where matter exhibits both particle-like and wave-like behavior, governed by probability amplitudes.",
        coreHighlight: "The Core Crux of R23: The entire unit revolves around the exact boundary state derivations for the 1D infinite potential well and the implications of the Heisenberg Uncertainty Principle.",
        concept1: { title: "Matter Waves", detail: "de Broglie proposed that moving particles have an associated wavelength λ = h/p." },
        concept2: { title: "Uncertainty", detail: "Heisenberg formulated that position and momentum cannot be simultaneously measured with arbitrary precision: Δx · Δp ≥ h/4π." },
        formula1: { title: "de Broglie Wavelength", eq: "λ = h / √(2mE)" },
        formula2: { title: "Particle in 1D Box", eq: "E_n = n²h² / (8mL²)" },
        pyq1: { title: "Schrödinger Time-Independent Eq", marks: "10 Marks", body: "Derive the time independent Schrödinger wave equation." },
        pyq2: { title: "Fermi Dirac Distribution", marks: "5 Marks", body: "Explain the effect of temperature on Fermi-Dirac distribution function." },
      },
      {
        id: "unit-3",
        title: "Intrinsic & Extrinsic Carrier Transport",
        subtitle: "Unit III: Semiconductors",
        weightage: "~15-20 Marks",
        desc: "Intrinsic/extrinsic transport, drift/diffusion, Fermi levels, and the Hall Effect.",
        introTitle: "Semiconductor Band Theory",
        introBody: "Materials are classified by energy band gaps. Semiconductors have a small band gap (~1 eV) allowing thermal excitation.",
        coreHighlight: "The Core Crux of R23: Hall effect derivation, Einstein relation, and intrinsic carrier concentration derivations dominate the board exams.",
        concept1: { title: "Charge Carriers", detail: "Electrons in conduction band and holes in valence band contribute to current." },
        concept2: { title: "Hall Effect", detail: "A transverse voltage is produced when a magnetic field is applied perpendicular to current flow." },
        formula1: { title: "Intrinsic Density", eq: "n_i² = N_c N_v exp(-E_g/kT)" },
        formula2: { title: "Hall Coefficient", eq: "R_H = 1 / (n·e)" },
        pyq1: { title: "Hall Effect Derivation", marks: "10 Marks", body: "Explain Hall Effect. Derive the expression for Hall coefficient." },
        pyq2: { title: "Einstein Relation", marks: "5 Marks", body: "Deduce the Einstein’s relation between diffusion coefficient and mobility." },
      },
      {
        id: "unit-4",
        title: "Einstein Coefficients & Fiber Optics",
        subtitle: "Unit IV: Lasers & Fiber Optics",
        weightage: "~10-15 Marks",
        desc: "Laser Characteristics, He-Ne laser, Nd:YAG. Numerical Aperture, Acceptance Angle derivations.",
        introTitle: "Principles of Light Emission",
        introBody: "Lasers operate on stimulated emission. Fiber optics rely on total internal reflection for guided light transmission.",
        coreHighlight: "The Core Crux of R23: He-Ne laser working mechanism and Numerical Aperture derivations are repeated every year.",
        concept1: { title: "Stimulated Emission", detail: "An incoming photon stimulates an excited atom to emit a coherent photon." },
        concept2: { title: "Total Internal Reflection", detail: "Light traveling from denser to rarer medium reflects completely if angle > critical angle." },
        formula1: { title: "Numerical Aperture", eq: "NA = √(n₁² - n₂²)" },
        formula2: { title: "Acceptance Angle", eq: "θ_a = arcsin(NA)" },
        pyq1: { title: "He-Ne Laser", marks: "10 Marks", body: "With a neat energy level diagram describe the working of He-Ne laser." },
        pyq2: { title: "Numerical Aperture", marks: "5 Marks", body: "Derive an expression for acceptance angle and numerical aperture." },
      },
      {
        id: "unit-5",
        title: "Polarization & Superconductors",
        subtitle: "Unit V: Dielectric & Magnetic Materials",
        weightage: "~10-15 Marks",
        desc: "Dielectrics polarizations; internal fields. Origin of magnetic moment, ferromagnetism, Superconducting transition.",
        introTitle: "Material Responses to Fields",
        introBody: "Dielectrics polarize in electric fields. Magnetic materials align dipoles in magnetic fields. Superconductors expel magnetic fields perfectly.",
        coreHighlight: "The Core Crux of R23: Clausius-Mossotti relation, B-H curve, and Meissner effect are the guaranteed questions.",
        concept1: { title: "Polarization", detail: "Electronic, ionic, and orientational displacement of charges." },
        concept2: { title: "Meissner Effect", detail: "Expulsion of magnetic field lines from a superconductor below critical temperature (perfect diamagnetism)." },
        formula1: { title: "Clausius-Mossotti", eq: "(ε_r - 1)/(ε_r + 2) = (N_α)/(3ε_o)" },
        formula2: { title: "Critical Field", eq: "H_c(T) = H_c(0)[1 - (T/T_c)²]" },
        pyq1: { title: "Clausius-Mossotti Relation", marks: "10 Marks", body: "Derive Clausius-Mossotti relation for solid dielectrics." },
        pyq2: { title: "Meissner Effect", marks: "5 Marks", body: "Write a short note on Meissner effect and Type I & II superconductors." },
      }
    ]
  },
  "Engineering Mathematics": {
    topicDesc: "Complete mapping of JNTUK Engineering Mathematics M1 & M2. From Matrix Eigenvalues to Multivariable Calculus.",
    units: [
      {
        id: "unit-1",
        title: "Matrix Operations & Linear Systems",
        subtitle: "Unit I: Matrices",
        weightage: "~15-20 Marks",
        desc: "Rank of matrix, Echelon form, Normal form. Solution of linear systems. Gauss elimination.",
        introTitle: "Linear Algebra Fundamentals",
        introBody: "Matrices provide a compact way to represent and solve systems of linear equations.",
        coreHighlight: "The Core Crux of R23: Finding the Rank using Echelon form and testing consistency of linear equations.",
        concept1: { title: "Rank of a Matrix", detail: "Number of non-zero rows in its row echelon form." },
        concept2: { title: "Gauss Elimination", detail: "Reducing a system to upper triangular form to solve via back substitution." },
        formula1: { title: "Consistency", eq: "Rank(A) = Rank(A|B) ≤ n" },
        formula2: { title: "Infinite Solutions", eq: "Rank(A) = Rank(A|B) &lt; n" },
        pyq1: { title: "Rank by Normal Form", marks: "10 Marks", body: "Reduce the matrix to Normal form and find its rank." },
        pyq2: { title: "System Consistency", marks: "10 Marks", body: "Test for consistency and solve: 2x - y + 3z = 8, -x + 2y + z = 4, 3x + y - 4z = 0." },
      },
      {
        id: "unit-2",
        title: "Eigenvalues, Eigenvectors & Orthogonal Transformation",
        subtitle: "Unit II: Eigen-Systems",
        weightage: "~15-20 Marks",
        desc: "Eigenvalues, Eigenvectors, Cayley-Hamilton Theorem, Diagonalization, Quadratic forms to canonical forms.",
        introTitle: "Eigen-Systems & Transformations",
        introBody: "Eigenvalues provide characteristic scale factors for matrix transformations. Cayley-Hamilton connects a matrix to its characteristic polynomial.",
        coreHighlight: "The Core Crux of R23: Finding Eigenvalues/vectors and reducing Quadratic form to Canonical form by Orthogonal Transformation.",
        concept1: { title: "Cayley-Hamilton Theorem", detail: "Every square matrix satisfies its own characteristic equation." },
        concept2: { title: "Quadratic Form", detail: "A homogenous polynomial of degree 2 in a number of variables." },
        formula1: { title: "Characteristic Eq", eq: "|A - λI| = 0" },
        formula2: { title: "Quadratic Form", eq: "Q = X^T A X" },
        pyq1: { title: "Cayley-Hamilton", marks: "10 Marks", body: "Verify Cayley-Hamilton theorem and find the inverse of A." },
        pyq2: { title: "Quadratic to Canonical", marks: "10 Marks", body: "Reduce the given quadratic form to canonical form by orthogonal reduction." }
      },
      {
        id: "unit-3",
        title: "Calculus & Mean Value Theorems",
        subtitle: "Unit III: Differential Calculus",
        weightage: "~15 Marks",
        desc: "Mean Value Theorems: Rolle's, Lagrange's, Cauchy's. Taylor's and Maclaurin's series.",
        introTitle: "Differential Calculus & Series",
        introBody: "Mean value theorems connect the local derivative of a function to its global change. Series expansions approximate complex functions with polynomials.",
        coreHighlight: "The Core Crux of R23: Verifying Rolle's/Lagrange's theorems and expanding functions using Maclaurin's series.",
        concept1: { title: "Rolle's Theorem", detail: "If f(a)=f(b) and continuous, there exists c where f'(c)=0." },
        concept2: { title: "Maclaurin Series", detail: "Expansion of a function about x=0." },
        formula1: { title: "Lagrange's MVT", eq: "f'(c) = (f(b) - f(a)) / (b - a)" },
        formula2: { title: "Cauchy's MVT", eq: "f'(c)/g'(c) = (f(b)-f(a))/(g(b)-g(a))" },
        pyq1: { title: "Verify Lagrange's MVT", marks: "5 Marks", body: "Verify Lagrange's mean value theorem for f(x) = log(x) on [1, e]." },
        pyq2: { title: "Maclaurin Expansion", marks: "10 Marks", body: "Expand tan(x) up to the term containing x^5 using Maclaurin's series." }
      },
      {
        id: "unit-4",
        title: "Partial Differentiation & Applications",
        subtitle: "Unit IV: Multivariable Calculus",
        weightage: "~15-20 Marks",
        desc: "Partial derivatives, Jacobians, Maxima and minima of functions of two variables, Lagrange multipliers.",
        introTitle: "Multivariable Calculus",
        introBody: "Extending calculus to functions of multiple variables. Critical for optimizing systems with multiple inputs.",
        coreHighlight: "The Core Crux of R23: Finding Maxima/Minima of two variables and applying Lagrange's method of undetermined multipliers.",
        concept1: { title: "Jacobian", detail: "Determinant of the Jacobian matrix, used in change of variables." },
        concept2: { title: "Lagrange Multipliers", detail: "Optimizing a function subject to equality constraints." },
        formula1: { title: "Total Derivative", eq: "dz = (∂z/∂x)dx + (∂z/∂y)dy" },
        formula2: { title: "Lagrange Function", eq: "L = f(x,y) + λφ(x,y)" },
        pyq1: { title: "Maxima & Minima", marks: "10 Marks", body: "Find the maximum and minimum values of x^3 + 3xy^2 - 15x^2 - 15y^2 + 72x." },
        pyq2: { title: "Jacobians", marks: "5 Marks", body: "If u = x+y, v = xy, find the Jacobian ∂(u,v)/∂(x,y)." }
      },
      {
        id: "unit-5",
        title: "Multiple Integrals",
        subtitle: "Unit V: Multiple Integration",
        weightage: "~15 Marks",
        desc: "Double and triple integrals, change of order of integration, change of variables, finding areas and volumes.",
        introTitle: "Multiple Integration",
        introBody: "Extending definite integrals to two and three dimensions for calculating areas, volumes, and center of mass.",
        coreHighlight: "The Core Crux of R23: Change of order of integration and evaluating double integrals over specific regions.",
        concept1: { title: "Change of Order", detail: "Swapping the limits of integration to simplify evaluation." },
        concept2: { title: "Polar Coordinates", detail: "Transforming Cartesian (x,y) to Polar (r,θ) where dx dy = r dr dθ." },
        formula1: { title: "Area via Double Integral", eq: "A = ∬ dx dy" },
        formula2: { title: "Volume via Triple Integral", eq: "V = ∭ dx dy dz" },
        pyq1: { title: "Change of Order", marks: "10 Marks", body: "Change the order of integration and evaluate ∬ xy dx dy." },
        pyq2: { title: "Area Calculation", marks: "5 Marks", body: "Find the area enclosed by the curves y = x^2 and y = x." }
      }
    ]
  },
  "Data Structures": {
    topicDesc: "Complete mapping of JNTUK Data Structures R23. From basic Arrays to advanced Graph traversal topologies.",
    units: [
      {
        id: "unit-1",
        title: "Arrays, Searching & Sorting",
        subtitle: "Unit I: Fundamentals",
        weightage: "~15 Marks",
        desc: "Array operations, Linear/Binary search. Selection, Bubble, Insertion, Quick, Merge sort.",
        introTitle: "Data Organization",
        introBody: "Organizing data efficiently is the foundation of computer science. Searching and sorting are the baseline mechanics.",
        coreHighlight: "The Core Crux of R23: Time complexity derivations for Merge Sort and Quick Sort.",
        concept1: { title: "Binary Search", detail: "O(log n) search on a sorted array by repeated halving." },
        concept2: { title: "Merge Sort", detail: "Divide and conquer recursive algorithm. Guaranteed O(n log n) time." },
        formula1: { title: "Binary Search Time", eq: "T(n) = T(n/2) + O(1)" },
        formula2: { title: "Merge Sort Time", eq: "T(n) = 2T(n/2) + O(n)" },
        pyq1: { title: "Quick Sort", marks: "10 Marks", body: "Trace Quick Sort on the array: [40, 20, 10, 80, 60, 50, 7, 30, 100]." },
        pyq2: { title: "Binary Search", marks: "5 Marks", body: "Write a C function for iterative Binary Search and state its complexity." },
      },
      {
        id: "unit-2",
        title: "Linked Lists (SLL, DLL, CLL)",
        subtitle: "Unit II: Dynamic Structures",
        weightage: "~15-20 Marks",
        desc: "Singly linked lists, doubly linked lists, circular linked lists, representation and operations.",
        introTitle: "Dynamic Data Structures",
        introBody: "Unlike arrays, linked lists allocate memory dynamically and do not require contiguous memory blocks.",
        coreHighlight: "The Core Crux of R23: Programmatic implementation of insertion and deletion in Singly and Doubly Linked Lists.",
        concept1: { title: "Singly Linked List", detail: "Each node contains data and a pointer to the next node." },
        concept2: { title: "Doubly Linked List", detail: "Each node contains pointers to both the previous and next nodes." },
        formula1: { title: "SLL Node Structure", eq: "struct Node { int data; struct Node* next; };" },
        formula2: { title: "DLL Node Structure", eq: "struct Node { int data; struct Node* prev, *next; };" },
        pyq1: { title: "SLL Operations", marks: "10 Marks", body: "Write a C program to insert a node at the beginning and end of a Singly Linked List." },
        pyq2: { title: "DLL Deletion", marks: "5 Marks", body: "Write an algorithm to delete a specific node from a Doubly Linked List." }
      },
      {
        id: "unit-3",
        title: "Stacks & Applications",
        subtitle: "Unit III: LIFO Operations",
        weightage: "~15 Marks",
        desc: "Stack properties, operations, array and linked list implementation, expression evaluation.",
        introTitle: "LIFO Operations",
        introBody: "Stacks follow the Last-In-First-Out (LIFO) principle. They are fundamental in recursion and parsing.",
        coreHighlight: "The Core Crux of R23: Conversion of infix to postfix expressions and evaluating postfix expressions.",
        concept1: { title: "Push & Pop", detail: "Push adds an element to the top; Pop removes the top element." },
        concept2: { title: "Expression Parsing", detail: "Using stacks to evaluate postfix expressions or check balanced parentheses." },
        formula1: { title: "Push Operation", eq: "stack[++top] = value;" },
        formula2: { title: "Pop Operation", eq: "value = stack[top--];" },
        pyq1: { title: "Infix to Postfix", marks: "10 Marks", body: "Convert the infix expression (A+B)*C-D/E into postfix notation using a stack." },
        pyq2: { title: "Stack via Linked List", marks: "10 Marks", body: "Implement Stack push and pop operations using Linked List." }
      },
      {
        id: "unit-4",
        title: "Queues & Deques",
        subtitle: "Unit IV: FIFO Operations",
        weightage: "~15 Marks",
        desc: "Queue properties, operations, circular queues, deques, implementation using arrays/linked lists.",
        introTitle: "FIFO Operations",
        introBody: "Queues operate strictly on First-In-First-Out (FIFO) logic, essential for scheduling and buffering.",
        coreHighlight: "The Core Crux of R23: Circular queue implementation and its advantage over simple queues.",
        concept1: { title: "Enqueue & Dequeue", detail: "Enqueue adds to the rear; Dequeue removes from the front." },
        concept2: { title: "Circular Queue", detail: "Connects the last position back to the first to utilize empty space efficiently." },
        formula1: { title: "CQ Enqueue", eq: "rear = (rear + 1) % MAX;" },
        formula2: { title: "CQ Dequeue", eq: "front = (front + 1) % MAX;" },
        pyq1: { title: "Circular Queue Operations", marks: "10 Marks", body: "Explain the implementation of Circular Queue with suitable C functions." },
        pyq2: { title: "Deque", marks: "5 Marks", body: "What is a Double Ended Queue (Deque)? Explain its input restricted variant." }
      },
      {
        id: "unit-5",
        title: "Trees, Hashing & Graphs",
        subtitle: "Unit V: Non-Linear Structures",
        weightage: "~20 Marks",
        desc: "Trees, Binary Search Tree (Insertion/Deletion/Traversal), Hashing collision techniques, Graph traversals.",
        introTitle: "Non-Linear Structures & Maps",
        introBody: "Hierarchical data is represented using Trees, while interconnected network systems use Graphs.",
        coreHighlight: "The Core Crux of R23: BST traversals (Inorder, Preorder, Postorder) and BFS/DFS graph traversals.",
        concept1: { title: "Binary Search Tree", detail: "Left child &lt; Root &lt; Right child, allowing efficient O(log n) searching." },
        concept2: { title: "Graph Traversal", detail: "BFS uses a Queue; DFS uses a Stack (or recursion)." },
        formula1: { title: "BST Property", eq: "Left_Val &lt; Root_Val &lt; Right_Val" },
        formula2: { title: "Hash Function", eq: "index = key % SIZE;" },
        pyq1: { title: "Tree Traversals", marks: "10 Marks", body: "Construct a BST for: 50, 30, 20, 40, 70, 60, 80. Write its Inorder, Preorder and Postorder." },
        pyq2: { title: "BFS and DFS", marks: "10 Marks", body: "Explain Breadth First Search (BFS) and Depth First Search (DFS) with an example." }
      }
    ]
  },
  "Chemistry": {
    topicDesc: "Complete mapping of JNTUK Engineering Chemistry R23. From Quantum Mechanics to Conducting Polymers and Instrumental Methods.",
    units: [
      {
        id: "unit-1",
        title: "Structure and Bonding Models",
        subtitle: "Unit I: Quantum Chemistry",
        weightage: "~15 Marks",
        desc: "Fundamentals of Quantum mechanics, Schrodinger Wave equation, Molecular orbital theory, Energy level diagrams of O2 and CO.",
        introTitle: "Quantum Chemistry Fundamentals",
        introBody: "Quantum mechanics provides the foundation for understanding atomic and molecular behavior through wave functions.",
        coreHighlight: "The Core Crux of R23: Molecular Orbital Theory (MOT) diagrams for homonuclear and heteronuclear diatomic molecules are frequently tested.",
        concept1: { title: "Schrödinger Equation", detail: "A fundamental equation describing how the quantum state of a quantum system changes with time." },
        concept2: { title: "Molecular Orbital Theory", detail: "Describes the electronic structure of molecules using atomic orbitals to form molecular orbitals." },
        formula1: { title: "Bond Order", eq: "BO = (N_b - N_a) / 2" },
        formula2: { title: "Schrödinger Eq", eq: "HΨ = EΨ" },
        pyq1: { title: "MOT of O2", marks: "10 Marks", body: "Draw the Molecular Orbital energy level diagram of O2 molecule and explain its magnetic behavior." },
        pyq2: { title: "Schrödinger Equation", marks: "10 Marks", body: "Derive the Schrodinger wave equation and explain the physical significance of Ψ and Ψ²." },
      },
      {
        id: "unit-2",
        title: "Modern Engineering Materials",
        subtitle: "Unit II: Advanced Materials",
        weightage: "~15-20 Marks",
        desc: "Semiconductors, Super Conductors, Super capacitors, and Nanomaterials (Fullerenes, Carbon Nanotubes, Graphenes).",
        introTitle: "Advanced Engineering Materials",
        introBody: "Modern engineering heavily relies on advanced materials like nanomaterials and superconductors for cutting-edge technology.",
        coreHighlight: "The Core Crux of R23: Preparation, properties, and applications of Carbon Nanotubes (CNTs) and Supercapacitors.",
        concept1: { title: "Superconductors", detail: "Materials that exhibit zero electrical resistance and expel magnetic fields perfectly below a critical temperature." },
        concept2: { title: "Carbon Nanotubes", detail: "Cylindrical carbon molecules with unique properties that make them potentially useful in nanotechnology." },
        formula1: { title: "Capacitance", eq: "C = Q / V" },
        formula2: { title: "Energy Stored", eq: "E = 1/2 CV²" },
        pyq1: { title: "Carbon Nanotubes", marks: "10 Marks", body: "Explain the arc-discharge and chemical vapour deposition methods for the synthesis of Carbon Nanotubes." },
        pyq2: { title: "Supercapacitors", marks: "5 Marks", body: "What are supercapacitors? Discuss their classification and applications." }
      },
      {
        id: "unit-3",
        title: "Electrochemistry and Applications",
        subtitle: "Unit III: Electrochemistry",
        weightage: "~15-20 Marks",
        desc: "Electrochemical cell, Nernst equation, potentiometry, primary and secondary cells, fuel cells (PEMFC).",
        introTitle: "Electrochemistry & Batteries",
        introBody: "Electrochemistry studies the relationship between electricity and identifiable chemical changes.",
        coreHighlight: "The Core Crux of R23: Working principles of Lithium-ion batteries, Nernst equation calculations, and Fuel cells.",
        concept1: { title: "Nernst Equation", detail: "Relates the reduction potential of an electrochemical reaction to the standard electrode potential, temperature, and activities." },
        concept2: { title: "Fuel Cells", detail: "Electrochemical cells that convert the chemical energy of a fuel and an oxidizing agent into electricity." },
        formula1: { title: "Nernst Equation", eq: "E = E° - (RT/nF)ln(Q)" },
        formula2: { title: "Cell Potential", eq: "E_cell = E_cathode - E_anode" },
        pyq1: { title: "Lithium-ion Battery", marks: "10 Marks", body: "Explain the construction, working, cell reactions, and advantages of a Lithium-ion battery." },
        pyq2: { title: "Nernst Equation", marks: "10 Marks", body: "Derive the Nernst equation for a single electrode potential and solve a related numerical problem." }
      },
      {
        id: "unit-4",
        title: "Polymer Chemistry",
        subtitle: "Unit IV: Polymers",
        weightage: "~15 Marks",
        desc: "Polymerization mechanisms, Plastics (PVC, Teflon, Bakelite), Elastomers (Buna-S), Conducting and Biodegradable polymers.",
        introTitle: "Polymer Science",
        introBody: "Polymers are large molecules composed of repeating structural units, crucial for everyday materials.",
        coreHighlight: "The Core Crux of R23: Preparation, properties, and applications of Bakelite, Teflon, and Conducting polymers like Polyacetylene.",
        concept1: { title: "Addition Polymerization", detail: "Monomers add to each other directly without the loss of any small molecules." },
        concept2: { title: "Conducting Polymers", detail: "Organic polymers that conduct electricity, often requiring doping." },
        formula1: { title: "Degree of Polymerization", eq: "DP = M_polymer / M_monomer" },
        formula2: { title: "Number Average Mol. Wt.", eq: "M_n = Σ(N_i M_i) / Σ(N_i)" },
        pyq1: { title: "Bakelite & Teflon", marks: "10 Marks", body: "Write the preparation, properties, and applications of Bakelite and Teflon." },
        pyq2: { title: "Conducting Polymers", marks: "10 Marks", body: "What are conducting polymers? Explain the mechanism of conduction in Polyacetylene." }
      },
      {
        id: "unit-5",
        title: "Instrumental Methods & Green Chemistry",
        subtitle: "Unit V: Spectroscopy & Energy",
        weightage: "~15-20 Marks",
        desc: "Beer-Lambert’s law, UV-Visible Spectroscopy, IR spectroscopy, Solar cells, Geothermal energy, Green chemistry.",
        introTitle: "Spectroscopy & Renewable Energy",
        introBody: "Analytical instrumentation is key for material characterization, while green chemistry promotes sustainable processes.",
        coreHighlight: "The Core Crux of R23: Beer-Lambert’s law derivations, Principles of UV/IR spectroscopy, and working of Solar cells.",
        concept1: { title: "Beer-Lambert's Law", detail: "The absorbance of light is directly proportional to the concentration of the absorbing species and path length." },
        concept2: { title: "Solar Cells", detail: "Devices that convert light energy directly into electrical energy via the photovoltaic effect." },
        formula1: { title: "Beer-Lambert's Law", eq: "A = ε c l" },
        formula2: { title: "Energy of Photon", eq: "E = hν = hc/λ" },
        pyq1: { title: "Beer-Lambert's Law", marks: "10 Marks", body: "State and explain Beer-Lambert's law. What are its limitations?" },
        pyq2: { title: "Solar Cells", marks: "10 Marks", body: "Explain the construction, working, and applications of a Photovoltaic (Solar) cell." }
      }
    ]
  },
  "Communicative English": {
    topicDesc: "Complete mapping of JNTUK Communicative English R23. Covering listening, speaking, reading, writing, and grammar.",
    units: [
      {
        id: "unit-1",
        title: "Human Values & Basic Grammar",
        subtitle: "Unit I: LSRW Basics",
        weightage: "~15 Marks",
        desc: "Gift of Magi (Short Story), skimming, scanning, mechanics of writing, basic sentence structures, synonyms, antonyms.",
        introTitle: "Foundations of Communication",
        introBody: "Developing core competencies in Listening, Speaking, Reading, and Writing to enable effective professional interactions.",
        coreHighlight: "The Core Crux of R23: Reading comprehension based on skimming/scanning and basic grammatical structures.",
        concept1: { title: "Skimming vs Scanning", detail: "Skimming gets the general idea; scanning finds specific information." },
        concept2: { title: "Mechanics of Writing", detail: "Proper capitalization, spelling, and punctuation." },
        formula1: { title: "Sentence Structure", eq: "Subject + Verb + Object" },
        formula2: { title: "Affixes", eq: "Prefix + Root + Suffix" },
        pyq1: { title: "Reading Comprehension", marks: "10 Marks", body: "Read the given passage and answer the questions based on skimming and scanning." },
        pyq2: { title: "Grammar & Vocabulary", marks: "5 Marks", body: "Identify the parts of speech in the given sentences and provide synonyms for the highlighted words." }
      },
      {
        id: "unit-2",
        title: "Nature & Cohesive Devices",
        subtitle: "Unit II: Paragraphs",
        weightage: "~15 Marks",
        desc: "The Brook by Alfred Tennyson, identifying sequence of ideas, paragraph writing, cohesive devices, homonyms.",
        introTitle: "Structuring Ideas",
        introBody: "Using cohesive devices to string ideas together into coherent paragraphs and understanding context in poetry.",
        coreHighlight: "The Core Crux of R23: Writing well-structured paragraphs using appropriate linkers and prepositions.",
        concept1: { title: "Cohesive Devices", detail: "Linkers and transition words that connect sentences and paragraphs logically." },
        concept2: { title: "Homonyms", detail: "Words that sound the same but have different meanings and spellings." },
        formula1: { title: "Paragraph Structure", eq: "Topic Sentence + Supporting Details + Concluding Sentence" },
        formula2: { title: "Articles", eq: "A, An, The, Zero Article" },
        pyq1: { title: "Paragraph Writing", marks: "10 Marks", body: "Write a cohesive paragraph on 'The Impact of Technology on Nature' using appropriate linkers." },
        pyq2: { title: "Prepositions and Articles", marks: "5 Marks", body: "Fill in the blanks with correct prepositions and articles in the provided text." }
      },
      {
        id: "unit-3",
        title: "Biography & Note-Making",
        subtitle: "Unit III: Summarizing",
        weightage: "~15-20 Marks",
        desc: "Elon Musk Biography, global comprehension, making inferences, summarizing, note-making, paraphrasing, tenses.",
        introTitle: "Information Processing",
        introBody: "Extracting key information from detailed texts, summarizing long passages, and maintaining verb tense consistency.",
        coreHighlight: "The Core Crux of R23: Creating accurate notes and summaries from detailed biographical texts.",
        concept1: { title: "Note-Making", detail: "Systematic method of writing down important information using headings and subheadings." },
        concept2: { title: "Paraphrasing", detail: "Rewriting text in your own words while maintaining the original meaning." },
        formula1: { title: "Summarizing", eq: "Main Idea + Key Points - Unnecessary Details" },
        formula2: { title: "Subject-Verb Agreement", eq: "Singular Subject -> Singular Verb" },
        pyq1: { title: "Note-Making", marks: "10 Marks", body: "Read the passage on Elon Musk and prepare structured notes using appropriate headings." },
        pyq2: { title: "Tenses & Agreement", marks: "5 Marks", body: "Correct the errors in subject-verb agreement and verb tenses in the given sentences." }
      },
      {
        id: "unit-4",
        title: "Inspiration & Official Writing",
        subtitle: "Unit IV: Business Communication",
        weightage: "~20 Marks",
        desc: "The Toys of Peace by Saki, graphic elements in texts, official letters, resumes, active & passive voice.",
        introTitle: "Professional Writing",
        introBody: "Mastering formal communication formats essential for the workplace, including official letters and resumes.",
        coreHighlight: "The Core Crux of R23: Resume preparation and formal letter writing formats are highly tested.",
        concept1: { title: "Resume Formatting", detail: "Clear presentation of education, skills, and experience for job applications." },
        concept2: { title: "Active vs Passive Voice", detail: "Active: Subject performs action. Passive: Subject receives action." },
        formula1: { title: "Formal Letter", eq: "Sender Address + Date + Receiver Address + Salutation + Body + Closing" },
        formula2: { title: "Passive Voice structure", eq: "Object + forms of 'be' + V3 + by + Subject" },
        pyq1: { title: "Resume Writing", marks: "10 Marks", body: "Draft a resume along with a cover letter applying for the position of Software Engineer." },
        pyq2: { title: "Voice Conversion", marks: "5 Marks", body: "Change the given sentences from active to passive voice." }
      },
      {
        id: "unit-5",
        title: "Motivation & Essay Writing",
        subtitle: "Unit V: Presentations",
        weightage: "~15 Marks",
        desc: "The Power of Intrapersonal Communication, formal oral presentations, structured essays, editing short texts.",
        introTitle: "Advanced Expression",
        introBody: "Developing the ability to present complex ideas orally and in structured essays, while self-editing for accuracy.",
        coreHighlight: "The Core Crux of R23: Writing structured essays on technical or motivational topics and editing grammar errors.",
        concept1: { title: "Structured Essay", detail: "Introduction (thesis), Body Paragraphs (arguments), Conclusion (summary)." },
        concept2: { title: "Text Editing", detail: "Identifying and correcting errors in articles, prepositions, tenses, and overall flow." },
        formula1: { title: "Essay Structure", eq: "Intro + Body 1, 2, 3 + Conclusion" },
        formula2: { title: "Presentation Flow", eq: "Hook -> Agenda -> Core Content -> Summary -> Q&A" },
        pyq1: { title: "Essay Writing", marks: "10 Marks", body: "Write a structured essay on 'The Importance of Intrapersonal Communication in Professional Success'." },
        pyq2: { title: "Editing", marks: "5 Marks", body: "Edit the following short text, correcting errors in tenses, prepositions, and articles." }
      }
    ]
  },
  "Basic Civil and Mechanical Engineering": {
    topicDesc: "Fundamentals of Civil and Mechanical Engineering. From structural materials to thermal engineering and robotics.",
    units: [
      {
        id: "unit-1",
        title: "Basics of Civil Engineering & Materials",
        subtitle: "Unit I: Civil Foundations",
        weightage: "~15 Marks",
        desc: "Role of Civil Engineers, disciplines, construction materials (cement, bricks, steel), prefabricated construction.",
        introTitle: "Introduction to Civil Infrastructure",
        introBody: "Understanding the different branches of civil engineering and the properties of common construction materials.",
        coreHighlight: "The Core Crux of R23: Classification of civil engineering disciplines and properties/uses of cement and steel.",
        concept1: { title: "Civil Disciplines", detail: "Structural, Geo-technical, Transportation, Hydraulics, and Environmental Engineering." },
        concept2: { title: "Construction Materials", detail: "Primary ingredients like Cement (binding), Aggregates (volume), and Steel (tensile strength)." },
        formula1: { title: "Concrete Mix", eq: "Cement + Sand + Aggregate + Water" },
        formula2: { title: "Steel Strength", eq: "High Tensile reinforcement" },
        pyq1: { title: "Civil Disciplines", marks: "10 Marks", body: "Explain the scope and importance of any four disciplines of Civil Engineering." },
        pyq2: { title: "Building Materials", marks: "5 Marks", body: "Discuss the role and properties of cement and steel in building construction." }
      },
      {
        id: "unit-2",
        title: "Surveying & Foundations",
        subtitle: "Unit II: Measurement & Support",
        weightage: "~15 Marks",
        desc: "Objectives of surveying, levelling instruments, contour mapping, types of foundations, bearing capacity.",
        introTitle: "Surveying and Ground Support",
        introBody: "Surveying determines relative positions of points. Foundations transfer building loads safely to the ground.",
        coreHighlight: "The Core Crux of R23: Calculation of reduced levels (Simple levelling problems) and types of foundations.",
        concept1: { title: "Levelling", detail: "Finding the elevation of points relative to a datum using instruments like a Dumpy level." },
        concept2: { title: "Bearing Capacity", detail: "The maximum load per unit area that the soil can support without failing." },
        formula1: { title: "Height of Instrument", eq: "HI = Reduced Level (RL) + Backsight (BS)" },
        formula2: { title: "New RL", eq: "RL = HI - Foresight (FS)" },
        pyq1: { title: "Levelling Problem", marks: "10 Marks", body: "Solve the simple levelling problem given the following consecutive readings." },
        pyq2: { title: "Foundations", marks: "5 Marks", body: "What are the requirements of a good foundation? List the types of shallow foundations." }
      },
      {
        id: "unit-3",
        title: "Transportation, Water & Environment",
        subtitle: "Unit III: Civil Infrastructure",
        weightage: "~15-20 Marks",
        desc: "Highway pavements, water quality specifications, rainwater harvesting, dams and reservoirs.",
        introTitle: "Macro Civil Systems",
        introBody: "Designing transportation networks and managing water resources for environmental sustainability.",
        coreHighlight: "The Core Crux of R23: Differences between flexible and rigid pavements, and methods of rainwater harvesting.",
        concept1: { title: "Pavements", detail: "Flexible (Bitumen, yields to loads) vs Rigid (Concrete, slab acts as a bridge)." },
        concept2: { title: "Rainwater Harvesting", detail: "Collecting and storing rainwater for future use, improving groundwater recharge." },
        formula1: { title: "Flexible Pavement", eq: "Load transferred grain to grain" },
        formula2: { title: "Rigid Pavement", eq: "Load transferred via slab action" },
        pyq1: { title: "Pavements", marks: "10 Marks", body: "Distinguish between flexible and rigid pavements with neat cross-sectional sketches." },
        pyq2: { title: "Water Resources", marks: "10 Marks", body: "Explain the importance of rainwater harvesting and describe any two methods." }
      },
      {
        id: "unit-4",
        title: "Basics of Mechanical & Thermal Engineering",
        subtitle: "Unit IV: Manufacturing & Heat",
        weightage: "~20 Marks",
        desc: "Engineering materials, casting, forming, machining, boilers, IC engines (SI/CI, 2-stroke/4-stroke).",
        introTitle: "Mechanical Systems & Heat",
        introBody: "Understanding how materials are manufactured into components and the principles of internal combustion engines.",
        coreHighlight: "The Core Crux of R23: Working of 4-stroke SI/CI engines and the differences between them.",
        concept1: { title: "Manufacturing Processes", detail: "Casting (molten metal), Forming (deformation), Machining (material removal)." },
        concept2: { title: "IC Engines", detail: "Spark Ignition (SI) uses petrol and a spark plug; Compression Ignition (CI) uses diesel and high compression." },
        formula1: { title: "Thermal Efficiency", eq: "η = Work Done / Heat Input" },
        formula2: { title: "Cycles", eq: "Otto (Const. Vol), Diesel (Const. Pressure)" },
        pyq1: { title: "4-Stroke Engine", marks: "10 Marks", body: "Explain the working principle of a 4-stroke Spark Ignition (SI) engine with a neat sketch." },
        pyq2: { title: "Manufacturing", marks: "10 Marks", body: "Briefly explain the principles of casting and welding processes." }
      },
      {
        id: "unit-5",
        title: "Power Plants, Transmission & Robotics",
        subtitle: "Unit V: Power & Automation",
        weightage: "~15 Marks",
        desc: "Steam/Hydro/Nuclear power plants. Belt, chain, gear drives. Introduction to robotics (joints, links, applications).",
        introTitle: "Power Generation & Motion",
        introBody: "Generating electricity via power plants, transmitting power through mechanical drives, and automating tasks via robots.",
        coreHighlight: "The Core Crux of R23: Working of Steam and Hydro electric power plants and comparisons of mechanical drives.",
        concept1: { title: "Power Plants", detail: "Steam (coal boils water), Hydro (water turns turbine), Nuclear (fission heat)." },
        concept2: { title: "Robotics", detail: "Mechanical systems structured with links and joints to perform programmed tasks." },
        formula1: { title: "Velocity Ratio (Belt)", eq: "N2/N1 = D1/D2" },
        formula2: { title: "Power Capacity", eq: "Gears > Chain > Belt" },
        pyq1: { title: "Power Plants", marks: "10 Marks", body: "Explain the working of a Hydro-electric power plant with a block diagram." },
        pyq2: { title: "Power Transmission", marks: "5 Marks", body: "Compare belt drives, chain drives, and gear drives in mechanical power transmission." }
      }
    ]
  },
  "C Programming": {
    topicDesc: "Complete mapping of JNTUK C Programming R23. From control structures and loops to files and pointers.",
    units: [
      {
        id: "unit-1",
        title: "C Fundamentals",
        subtitle: "Unit I: Basics",
        weightage: "~15 Marks",
        desc: "Structure of C, data types, operators, input/output.",
        introTitle: "Foundations of C",
        introBody: "Understanding C programming basics, structure, and standard libraries.",
        coreHighlight: "The Core Crux of R23: Writing standard C programs and understanding variables/operators.",
        concept1: { title: "Data Types", detail: "Int, float, char, double fundamental types." },
        concept2: { title: "Operators", detail: "Arithmetic, logical, relational, bitwise operators." },
        formula1: { title: "C Program Structure", eq: "#include -> main() -> { ... }" },
        formula2: { title: "Basic I/O", eq: "printf() for output, scanf() for input" },
        pyq1: { title: "Structure of C", marks: "10 Marks", body: "Describe the structure of a C program with an example." },
        pyq2: { title: "Operators", marks: "5 Marks", body: "Classify and explain different operators in C." }
      },
      {
        id: "unit-2",
        title: "Control Structures & Loops",
        subtitle: "Unit II: Logic Flow",
        weightage: "~15-20 Marks",
        desc: "Decision making (if, if-else, switch), loops (for, while, do-while), break, continue.",
        introTitle: "Control Flow in C",
        introBody: "Mastering conditional branching and repetitive execution logic for complex algorithm design.",
        coreHighlight: "The Core Crux of R23: Efficient use of nested loops and switch-case branching mechanics.",
        concept1: { title: "Decision Making", detail: "Controlling flow using if, if-else, and switch constructs." },
        concept2: { title: "Iteration", detail: "Using for, while, do-while for controlled repetitive tasks." },
        formula1: { title: "Loop Structure", eq: "init; condition; increment/decrement" },
        formula2: { title: "Switch Case", eq: "switch(var) { case val: ... default: ... }" },
        pyq1: { title: "Nested Loops", marks: "10 Marks", body: "Write a program to print a pyramid pattern using nested loops." },
        pyq2: { title: "Switch-Case", marks: "5 Marks", body: "Explain the switch statement with a program." }
      },
      {
        id: "unit-3",
        title: "Functions, Arrays & Strings",
        subtitle: "Unit III: Modularity & Collections",
        weightage: "~15 Marks",
        desc: "Function types, parameter passing (by val/ref), 1D/2D arrays, string manipulation functions.",
        introTitle: "Modular Programming",
        introBody: "Breaking programs into reusable functions and managing collections via arrays and strings.",
        coreHighlight: "The Core Crux of R23: Handling 2D arrays (matrices) and string library functions effectively.",
        concept1: { title: "Functions", detail: "Modularizing code using prototypes, definition, and calls." },
        concept2: { title: "Arrays & Strings", detail: "Contiguous storage for homogeneous data and null-terminated character sequences." },
        formula1: { title: "Function call", eq: "retType funcName(params);" },
        formula2: { title: "2D Array Indexing", eq: "arr[row][col]" },
        pyq1: { title: "Matrix Multiplication", marks: "10 Marks", body: "Write a C program to perform matrix multiplication using 2D arrays." },
        pyq2: { title: "String Manipulation", marks: "10 Marks", body: "Explain different string manipulation functions in <string.h>." }
      },
      {
        id: "unit-4",
        title: "Pointers & Structures",
        subtitle: "Unit IV: Memory & Definitions",
        weightage: "~20 Marks",
        desc: "Pointer arithmetic, dereferencing, void pointers, structs, nested structures, union.",
        introTitle: "Memory & Data Definitions",
        introBody: "Direct memory management via pointers and defining custom data aggregate types via structs.",
        coreHighlight: "The Core Crux of R23: Pointer-array interaction and nested structure implementation.",
        concept1: { title: "Pointers", detail: "Storing memory addresses of variables for indirect access." },
        concept2: { title: "Structures", detail: "Aggregating heterogeneous data types into a single unit." },
        formula1: { title: "Pointer Arithmetic", eq: "ptr + offset" },
        formula2: { title: "Struct Access", eq: "structVar.member | ptr->member" },
        pyq1: { title: "Pointers & Arrays", marks: "10 Marks", body: "Explain the relationship between pointers and arrays with an example." },
        pyq2: { title: "Nested Structures", marks: "10 Marks", body: "Write a program to demonstrate nested structures." }
      },
      {
        id: "unit-5",
        title: "Files & Preprocessor",
        subtitle: "Unit V: Secondary Storage & Macros",
        weightage: "~15 Marks",
        desc: "File modes (read/write/append), fopen/fclose, fprintf/fscanf, preprocessor directives (#define, #include).",
        introTitle: "I/O & Directives",
        introBody: "Interacting with secondary storage for data persistence and mastering preprocessor directives for conditional compilation.",
        coreHighlight: "The Core Crux of R23: Safe handling of files and defining parametric macros.",
        concept1: { title: "File Operations", detail: "Managing storage via fopen, fclose, fprintf, fscanf." },
        concept2: { title: "Preprocessor", detail: "Directives like #define, #include, #if for source code manipulation." },
        formula1: { title: "File Open", eq: "FILE *fptr = fopen(filename, mode);" },
        formula2: { title: "Parametric Macro", eq: "#define SQUARE(x) ((x)*(x))" },
        pyq1: { title: "File Copying", marks: "10 Marks", body: "Write a program to copy the contents of one file to another." },
        pyq2: { title: "Preprocessors", marks: "10 Marks", body: "Explain various preprocessor directives in C with examples." }
      }
    ]
  }
};
